local data = 
{
[1]={
["cs_life"]="生命值", 
["cs_skills"]="技能ID", 
["cs_attack"]="攻击力", 
["cs_type"]="使用类型", 
["cs_map"]="获取该物品的地图难度，章，节", 
["cs_defense"]="防御力", 
["cs_time"]="有效时间", 
["cs_diamonds"]="钻石", 
["cs_gold"]="金币", 
["cs_exp"]="经验值", 
["cs_itemid"]="物品ID", 
["cs_max"]="每个背包格子最多数量", 
}
, 
[2]={
["cs_life"]=4, 
["cs_skills"]=2, 
["cs_attack"]=5, 
["cs_type"]="被动消费", 
["cs_map"]="例子1;2;2||2;3;3", 
["cs_defense"]=6, 
["cs_time"]=1, 
["cs_diamonds"]=8, 
["cs_gold"]=7, 
["cs_exp"]=3, 
["cs_itemid"]=1, 
["cs_max"]=9, 
}
, 
[3]={
["cs_life"]="null", 
["cs_skills"]="null", 
["cs_attack"]="null", 
["cs_type"]="主动消费", 
["cs_map"]="null", 
["cs_defense"]="null", 
["cs_time"]="null", 
["cs_diamonds"]="null", 
["cs_gold"]="null", 
["cs_exp"]="null", 
["cs_itemid"]="null", 
["cs_max"]="null", 
}
, 
}
return data
