local data = 
{
[1]={
["login"]="demo1背景图", 
["name"]="名字", 
["id"]=1, 
["tag"]="标志", 
["res"]="资源", 
["change_scene"]="切换类型", 
["menu2"]="背景2", 
["menu1"]="背景1", 
}
, 
[2]={
["login"]="null", 
["name"]="menu", 
["id"]=2, 
["tag"]="null", 
["res"]="NewUI_1.json", 
["change_scene"]=12, 
["menu2"]="res/ui/menu2.png", 
["menu1"]="res/ui/menu.png", 
}
, 
[3]={
["login"]="null", 
["name"]="start", 
["id"]=3, 
["tag"]=44, 
["res"]="null", 
["change_scene"]="null", 
["menu2"]="null", 
["menu1"]="null", 
}
, 
[4]={
["login"]="login_1.json", 
["name"]="demo1", 
["id"]=4, 
["tag"]="null", 
["res"]="null", 
["change_scene"]="null", 
["menu2"]="null", 
["menu1"]="null", 
}
, 
[5]={
["login"]="null", 
["name"]="loginame", 
["id"]=5, 
["tag"]=21, 
["res"]="null", 
["change_scene"]="null", 
["menu2"]="null", 
["menu1"]="null", 
}
, 
}
return data
